# Generated by Django 2.2.12 on 2020-04-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='college',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='college',
            field=models.ManyToManyField(null=True, to='api.College'),
        ),
    ]
