# Generated by Django 2.2.12 on 2020-04-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200419_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='certification',
            field=models.ManyToManyField(to='api.Certification'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project',
            field=models.ManyToManyField(to='api.Project'),
        ),
    ]
