# Generated by Django 2.2.12 on 2020-04-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200419_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='skills',
            new_name='skill',
        ),
    ]
