# Generated by Django 2.2.12 on 2020-04-20 21:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200419_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='avatar',
            field=models.ImageField(null=True, upload_to=api.models.portfolio_avatar_file_path),
        ),
    ]
