                          List of relations
 Schema |                  Name                   |   Type   | Owner  
--------+-----------------------------------------+----------+--------
 public | api_about                               | table    | mysite
 public | api_about_id_seq                        | sequence | mysite
 public | api_achievement                         | table    | mysite
 public | api_achievement_id_seq                  | sequence | mysite
 public | api_certification                       | table    | mysite
 public | api_certification_id_seq                | sequence | mysite
 public | api_college                             | table    | mysite
 public | api_college_id_seq                      | sequence | mysite
 public | api_company                             | table    | mysite
 public | api_company_id_seq                      | sequence | mysite
 public | api_interest                            | table    | mysite
 public | api_interest_id_seq                     | sequence | mysite
 public | api_message                             | table    | mysite
 public | api_message_id_seq                      | sequence | mysite
 public | api_portfolio                           | table    | mysite
 public | api_portfolio_about                     | table    | mysite
 public | api_portfolio_about_id_seq              | sequence | mysite
 public | api_portfolio_achievement               | table    | mysite
 public | api_portfolio_achievement_id_seq        | sequence | mysite
 public | api_portfolio_certification             | table    | mysite
 public | api_portfolio_certification_id_seq      | sequence | mysite
 public | api_portfolio_education                 | table    | mysite
 public | api_portfolio_education_id_seq          | sequence | mysite
 public | api_portfolio_id_seq                    | sequence | mysite
 public | api_portfolio_interest                  | table    | mysite
 public | api_portfolio_interest_id_seq           | sequence | mysite
 public | api_portfolio_project                   | table    | mysite
 public | api_portfolio_project_id_seq            | sequence | mysite
 public | api_portfolio_skill                     | table    | mysite
 public | api_portfolio_skill_id_seq              | sequence | mysite
 public | api_portfolio_work_experience           | table    | mysite
 public | api_portfolio_work_experience_id_seq    | sequence | mysite
 public | api_profilefeeditem                     | table    | mysite
 public | api_profilefeeditem_id_seq              | sequence | mysite
 public | api_project                             | table    | mysite
 public | api_project_id_seq                      | sequence | mysite
 public | api_skill                               | table    | mysite
 public | api_skill_id_seq                        | sequence | mysite
 public | api_userprofile                         | table    | mysite
 public | api_userprofile_groups                  | table    | mysite
 public | api_userprofile_groups_id_seq           | sequence | mysite
 public | api_userprofile_id_seq                  | sequence | mysite
 public | api_userprofile_user_permissions        | table    | mysite
 public | api_userprofile_user_permissions_id_seq | sequence | mysite
 public | auth_group                              | table    | mysite
 public | auth_group_id_seq                       | sequence | mysite
 public | auth_group_permissions                  | table    | mysite
 public | auth_group_permissions_id_seq           | sequence | mysite
 public | auth_permission                         | table    | mysite
 public | auth_permission_id_seq                  | sequence | mysite
 public | authtoken_token                         | table    | mysite
 public | django_admin_log                        | table    | mysite
 public | django_admin_log_id_seq                 | sequence | mysite
 public | django_content_type                     | table    | mysite
 public | django_content_type_id_seq              | sequence | mysite
 public | django_migrations                       | table    | mysite
 public | django_migrations_id_seq                | sequence | mysite
 public | django_session                          | table    | mysite
(58 rows)

